### ISSUE TITLE
魅族 mx2 android 4.4.4，无法运行，即一点击就提示停止运行

### ISSUE THREAD

**Issue by hnyzwtf** [xcc3641/SeeWeather#32]
这是错误日志：
07-29 17:23:09.679 14837-14837/com.xiecc.seeWeather E/CrashHandler: (ThreadGroup.java:693) java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xiecc.seeWeather/com.xiecc.seeWeather.modules.main.ui.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
07-29 17:23:09.684 14837-14837/com.xiecc.seeWeather E/CrashHandler: (ThreadGroup.java:693) 2.2  M045  4.4.4  Meizu
07-29 17:23:09.694 14837-14837/com.xiecc.seeWeather E/CrashHandler: (ThreadGroup.java:693) java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xiecc.seeWeather/com.xiecc.seeWeather.modules.main.ui.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5117)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                        at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:198)
                                                                        at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:130)
                                                                        at com.xiecc.seeWeather.modules.main.ui.MainActivity.initView(MainActivity.java:108)
                                                                        at com.xiecc.seeWeather.modules.main.ui.MainActivity.onCreate(MainActivity.java:65)
                                                                        at android.app.Activity.performCreate(Activity.java:5340)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:136) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5117) 
                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                        at dalvik.system.NativeStart.main(Native Method) 
07-29 17:23:09.719 14837-14837/com.xiecc.seeWeather I/LiteOrm: data has cleared. delete Database path: /data/data/com.xiecc.seeWeather/databases/cities.db
07-29 17:23:09.724 14837-14837/com.xiecc.seeWeather E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.xiecc.seeWeather, PID: 14837
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xiecc.seeWeather/com.xiecc.seeWeather.modules.main.ui.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5117)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:198)
                                                                          at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:130)
                                                                          at com.xiecc.seeWeather.modules.main.ui.MainActivity.initView(MainActivity.java:108)
                                                                          at com.xiecc.seeWeather.modules.main.ui.MainActivity.onCreate(MainActivity.java:65)
                                                                          at android.app.Activity.performCreate(Activity.java:5340)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5117) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by xcc3641** [comment]
我的锅 主题那里写错了  更新下代码试试吧？
